#!/bin/bash
# Originally by Kris Occhipinti
# https://www.youtube.com/watch?v=FsQuGplQvrw
# Needs mpv, xsel 
# Elvis Donald Attro

notify-send -t 3000 "Playing Video" "$(xsel -o)";
mpv --ytdl-format=bestvideo+bestaudio/best --fs --speed=1.0 --af=rubberband=pitch-scale=0.981818181818181 "$(xsel -o)"
