#!/bin/bash
# Originally by Kris Occhipinti
# https://www.youtube.com/watch?v=FsQuGplQvrw
# Needs mpv, xsel 
# Elvis Donald Attro

link="$(xsel -o)"
title=$(youtube-dl --skip-download --get-title "$link")
notify-send -t 3000 "Playing Video" "$title";
mpv --ytdl-format=bestvideo+bestaudio/best --fs --speed=1.0 "$link"
