#!/bin/sh

# I just find them in default .xinitrc
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Export locale variables
# I use autox for Display Manager replacement
# It has a bug that make locale configurations are not loaded on login
# (Confirmed in Void Wiki)
# So I export the locale configurations manually
# Without this some character in terminal couldn't be loaded
export LANG=en_US.utf8
export LC_COLLATE=C
export LC_ADDRESS=en_US.utf8
export LC_CTYPE=en_US.utf8
export LC_IDENTIFICATION=en_US.utf8
export LC_MEASUREMENT=id_ID.utf8
export LC_MESSAGES=en_US.utf8
export LC_MONETARY=id_ID.utf8
export LC_NAME=en_US.utf8
export LC_NUMERIC=id_ID.utf8
export LC_PAPER=en_US.utf8
export LC_TELEPHONE=id_ID.utf8
export LC_TIME=en_US.utf8
export LC_ALL=en_US.UTF-8

# Default xinit config file
#export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc

# XDG Base Directory Specification
# System dirs
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_RUNTIME_DIR=/var/tmp/${USER}/xdgr
export RCRC=${XDG_CONFIG_HOME}/rcrc

# User dirs
export XDG_DOWNLOAD_DIR="$HOME/dl"
export XDG_DOCUMENTS_DIR="$HOME/docs"
export XDG_MUSIC_DIR="$HOME/sds"
export XDG_PICTURES_DIR="$HOME/pics"
export XDG_VIDEOS_DIR="$HOME/vids"

export BROWSER=firefox
export MPD_MUSIC_DIRECTORY="/media/Entertainment/Music Museum/MyMusic"

export PATH=$PATH:/usr/local/bin:/usr/local/sbin:$HOME/.local/bin

# Launch Bspwm
# I put every autostart in bspwmrc
exec bspwm
