#!/bin/bash

## Coloring
source ~/code/scripts/getcolors

xrdb $XDG_CONFIG_HOME/X11/Xresources
COLOR=$(shuf -n1 -e $XDG_CONFIG_HOME/colors/*)
SHORTCOLOR=$(echo $COLOR | sed "s@.*/@@")
xrdb -merge $COLOR
paintee
# Only use the function above if the cache of paintee couldn't be found
if [ -e ~/.cache/paintee ]; then
	. ~/.cache/paintee
	else
	getcolors
fi

## Bspwm configurations
bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI'
bspc config focus_follows_pointer true
bspc config border_width 4
bspc config window_gap 8
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config top_padding 32
bspc config right_padding 8
bspc config bottom_padding 8
bspc config left_padding 8

## Window rules
# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a st desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a Firefox desktop='^2' follow=on focus=on

# 3 > file
# 4 > office
declare -a office=(Gucharmap \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 5 > media
declare -a media=(zoom mpv)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

# 6 > settings
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# special rules
bspc rule -a Zathura state=tiled follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a sixv state=tilled follow=on focus=on

## Autostart
xsetroot -cursor_name left_ptr
xbacklight -set 10
xset fp+ $XDG_DATA_HOME/fonts/misc
killall -9 sxhkd picon vanela xsettingsd redshift xbanish dunst
sxhkd &
picom -CG --experimental-backends &
vanela &
xsettingsd &
redshift &
xbanish -i shift -i control -i mod1 -i mod4 &
WALLPAPER=$(shuf -n1 -e ~/pics/.wallpaper/*)
SHORTWALLPAPER=$(echo $WALLPAPER | sed "s@.*/@@" | sed "s/\..*$//")
ls ~/pics/.wallpaper | sort -R | tail -$N | while read file; do # useless animation
hsetroot -fill ~/pics/.wallpaper/$file -tint '#3c6f86'; sleep 0.1; done
hsetroot -fill $WALLPAPER -tint '#9ccfe6'
dunst &
sleep 0.5
notify-send "Bspwm Loaded" "With $SHORTCOLOR color and $SHORTWALLPAPER wallpaper"
